import { type NextPage } from 'next';
import Head from 'next/head';

import CharacterContainer from '../components/CharacterContainer';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Comp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="">
        {/* <CreateCompPage /> */}
        <div>
          <CharacterContainer />
        </div>
      </main>
    </>
  );
};

export default Home;
