import { type NextPage } from 'next';
import Head from 'next/head';
import CreateCompPage from './create-comp-page';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Comp</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/ashe.ico" />
      </Head>
      <main className="">
        <CreateCompPage />
      </main>
    </>
  );
};

export default Home;
